import {reviewEconomics} from './review-economics.mjs';
import {researchApplication,libraryAnalysis} from './library-analysis.mjs';
import practice from './research/practice.json' with {type:'json'};
import studies from './research/studies.json' with {type:'json'};
import strategies from './research/strategies.json' with {type:'json'};
import libraries from './research/libraries.json' with {type:'json'};
import practiceDe from './research/de/practice.json' with {type:'json'};
import studiesDe from './research/de/studies.json' with {type:'json'};
import strategiesDe from './research/de/strategies.json' with {type:'json'};
import librariesDe from './research/de/libraries.json' with {type:'json'};
import catalogue from '../packages/writing-rules/src/catalogue.json' with {type:'json'};
import {escape as e} from './template.mjs';

export const researchGroups={practice,studies,strategies,libraries};
export const researchGroupsByLocale={en:researchGroups,de:{practice:practiceDe,studies:studiesDe,strategies:strategiesDe,libraries:librariesDe}};
const records=Object.values(researchGroups).flat();
const ruleIds=new Set(catalogue.rules.map(rule=>rule.id));
for(const [locale,groups] of Object.entries(researchGroupsByLocale)){
  const ids=new Set();
  for(const record of Object.values(groups).flat()){
    if(!record.id||ids.has(record.id)||!/^https:\/\//.test(record.url)||!record.relatedRuleIds.every(id=>ruleIds.has(id)))throw new Error('Invalid '+locale+' research record: '+record.id);
    ids.add(record.id);
  }
  for(const [key,group] of Object.entries(groups)){
    if(group.length!==researchGroups[key].length||group.some((record,index)=>record.id!==researchGroups[key][index].id||record.url!==researchGroups[key][index].url))throw new Error('Research translation source mismatch: '+locale+'/'+key);
  }
}
const paragraphs=items=>items.map(item=>`<p>${e(item)}</p>`).join('');
const authors=record=>record.authors.length>2?record.authors.slice(0,2).join(', ')+' et al.':record.authors.join(', ');
const field=(name,text)=>`<dt>${e(name)}</dt><dd>${Array.isArray(text)?paragraphs(text):e(text)}</dd>`;
const cite=(id,label)=>{const record=records.find(record=>record.id===id);if(!record)throw new Error('Unknown research citation: '+id);return `<a href="${e(record.url)}">${e(label)}</a>`};
const apiReference={
  getWritingRule:'../guides/writing-rules/',selectWritingRules:'../guides/writing-rules/',
  composeWritingReviewPrompt:'../guides/writing-rules/',findWritingSignals:'../guides/writing-rules/',
  mountVoiceReview:'../guides/library/'
};
function apiUse(record,locale){
  const de=locale==='de',use=record.apiUse;
  if(!use||!use.availableNow.length||use.availableNow.some(api=>!Object.hasOwn(apiReference,api.symbol)))throw new Error('Missing or invalid research API connection: '+record.id);
  return `<section class="research-api" aria-label="${de?'Bezug zur API':'API connection'}"><h3>${de?'Anwendung in Voice':'Use with Voice'}</h3><p>${e(use.currentUse)}</p><ul>${use.availableNow.map(api=>`<li><a href="${apiReference[api.symbol]}"><code>${e(api.symbol)}</code></a> — ${e(api.purpose)}</li>`).join('')}</ul><p><strong>${de?'Was noch fehlt:':'What is missing:'}</strong> ${e(use.missingCapability)}</p></section>`;
}
function rules(record,locale){
  return `<p class="research-rules">${locale==='de'?'Zugehörige Muster:':'Related patterns:'} ${record.relatedRuleIds.map(id=>`<a href="../writing-patterns/#${locale}-${e(id)}">${e(catalogue.rules.find(rule=>rule.id===id).antiPattern.name[locale])}</a>`).join(' · ')}</p>`;
}
function sourceMeta(record,locale){
  const de=locale==='de';
  return `<p class="research-meta">${e(authors(record))} · ${e(record.date||(de?'Ohne Datum; abgerufen am 12. September 2026':'Undated; accessed 12 September 2026'))} · <a href="${e(record.url)}">${de?'Originalquelle':'Original source'}</a></p>`;
}
function entry(record,locale){
  const de=locale==='de',prefix=de?'de-':'',t=(en,dt)=>de?dt:en;
  const isStudy=record.kind==='study',isStrategy=record.kind==='strategy-evidence';
  const brief=isStudy?record.question:isStrategy?record.application.replace(/^(Voice implication|Folgerung für Voice|Anwendung in Voice): /,''):record.voiceImplication;
  return `<details class="research-entry" id="${prefix}${e(record.id)}"><summary>${e(record.title)}<span>${e(brief)}</span></summary><div class="research-detail">${sourceMeta(record,locale)}<dl>${isStudy?field(t('Method','Methode'),record.method)+field(t('Findings','Ergebnisse'),record.findings)+field(t('Limits','Grenzen'),record.limitations):isStrategy?field(t('Method','Methode'),record.method)+field(t('Finding','Ergebnis'),record.finding)+field(t('Limits','Grenzen'),record.limits):field(t('Observation','Beobachtung'),record.observation)+field(t('Limits','Grenzen'),record.limits)}${isStudy?field(t('Implication for Voice','Folgerung für Voice'),record.voiceImplication):''}</dl>${apiUse(record,locale)}${rules(record,locale)}<p class="research-meta">${e(record.readingDepth)}</p></div></details>`;
}
function library(record,locale){
  const de=locale==='de',prefix=de?'de-':'',t=(en,dt)=>de?dt:en;
  return `<details class="research-entry" id="${prefix}${e(record.id)}"><summary>${e(record.name)}<span>${e(record.voiceFit.replace(/^(Assessment|Einschätzung): /,''))}</span></summary><div class="research-detail"><p><a href="${e(record.url)}">${t('Official repository','Offizielles Repository')}</a> · <a href="${e(record.license.url)}">${e(record.license.id)} ${t('license','Lizenz')}</a></p><dl>${field(t('Execution','Ausführung'),record.execution)}${field(t('Languages','Sprachen'),record.languageSupport)}${field(t('Capabilities','Funktionen'),record.capabilities)}${field(t('Limits','Grenzen'),record.limits)}${field(t('Maintenance snapshot · ','Projektpflege · Stand ')+record.maintenance.checkedAt,record.maintenance.observation)}</dl>${apiUse(record,locale)}${rules(record,locale)}<ul>${record.refs.map(ref=>`<li><a href="${e(ref.url)}">${e(ref.title)}</a></li>`).join('')}</ul></div></details>`;
}
export function researchIntro(locale='en'){
  const de=locale==='de',prefix=de?'de-':'';
  return `<header class="research-heading"><p class="research-date">${de?'Voice Forschung · 12. September 2026':'Voice Research · 12 September 2026'}</p><h1>${de?'KI-Texte, die man gern liest.':'AI writing worth reading.'}</h1><p class="lead">${de?'Forschung zu KI-Texten, redaktionellen Regeln und der Qualität von Reviews.':'Research on AI writing, editing rules and review quality.'}</p><p><a href="../writing-patterns/">${de?'Negativmuster und Gegen-Prompts lesen':'Read the anti-patterns and counter-prompts'} ↗</a></p><nav class="research-nav" aria-label="${de?'Forschungsthemen':'Research topics'}">${[['findings','Findings','Befunde'],['practice','Practice articles','Praxisartikel'],['studies','Studies','Studien'],['strategies','Counter-strategies','Gegenstrategien'],['libraries','Libraries','Bibliotheken'],['library-analysis','Library analysis','Analysefunktionen'],['voice','Review workflow','Review-Ablauf'],['economics','Review quality and cost','Qualität und Kosten'],['sources','Sources & data','Quellen & Daten']].map(([id,en,dt])=>`<a href="#${prefix}${id}">${de?dt:en}</a>`).join('')}</nav></header>`;
}
export function researchContent(locale='en'){
  locale=locale==='de'?'de':'en';
  const de=locale==='de',prefix=de?'de-':'',t=(en,dt)=>de?dt:en;
  const {practice,studies,strategies,libraries}=researchGroupsByLocale[locale];
  const localizedRecords=Object.values(researchGroupsByLocale[locale]).flat();
  return `<section class="research-content" lang="${locale}" aria-label="${t('Research analysis and source collection','Forschungsanalysen und Quellensammlung')}">
<section id="${prefix}findings" class="research-findings"><h2>${t('What the evidence changes','Was aus den Befunden folgt')}</h2>
<h3>${t("Review the reader's problem",'Vom Anliegen der Leser ausgehen')}</h3><p>${t("Relevance, information density and tone helped explain expert judgments in <em>Measuring AI ‘Slop’</em>. Agreement was stronger on problematic passages than on a binary label.",'Relevanz, Informationsdichte und Ton halfen in <em>Measuring AI ‘Slop’</em>, die Urteile der Fachleute zu erklären. Bei problematischen Textstellen stimmten sie häufiger überein als bei der pauschalen Einordnung als „Slop“.')} ${cite('shaib-slop-2025',t('Shaib et al., preprint, revised 2026','Shaib et al., Preprint, überarbeitet 2026'))}.</p><p>${t("For Voice, this supports a contextual question: which passage prevents the reader from understanding, deciding or acting? Word matches can locate candidates; the page's purpose determines whether they need changing.",'Für Voice folgt daraus: Welche Textstelle erschwert es, etwas zu verstehen, zu entscheiden oder zu tun? Worttreffer können auf solche Stellen hinweisen. Ob eine Änderung hilft, hängt vom Zweck der Seite ab.')}</p>
<h3>${t('Better individual texts can still become more alike','Bessere Einzeltexte können sich stärker ähneln')}</h3><p>${t('In a randomized short-story experiment, AI ideas improved ratings while assisted stories became more similar. This is evidence for assessing usefulness and distinctiveness separately.','In einem randomisierten Experiment mit Kurzgeschichten verbesserten KI-Ideen die Bewertungen. Zugleich ähnelten sich die so entstandenen Geschichten stärker. Das spricht dafür, Nutzen und Eigenständigkeit getrennt zu beurteilen.')} ${cite('doshi-creativity-diversity-2024',t('Doshi and Hauser, 2024','Doshi und Hauser, 2024'))}.</p><p>${t('In a contextual review, compare repeated framing across a page and across proposed alternatives. Three rewrites that merely swap synonyms offer little choice. A deliberate rhythm or an accepted headline can remain effective.','Ein Review sollte wiederkehrende Formulierungen und Argumentationsmuster auf der ganzen Seite und zwischen den vorgeschlagenen Alternativen vergleichen. Drei Fassungen mit anderen Synonymen bieten kaum Auswahl. Ein bewusst gewählter Rhythmus oder eine bereits akzeptierte Überschrift kann dagegen gut funktionieren.')}</p>
<h3>${t('A familiar word is a clue with a narrow scope','Ein auffälliges Wort erlaubt nur begrenzte Schlüsse')}</h3><p>${t('Corpus research detects abrupt vocabulary shifts; it cannot identify the origin of an individual passage.','Korpusstudien erkennen abrupte Veränderungen im Wortgebrauch. Daraus lässt sich die Herkunft einer einzelnen Textstelle nicht bestimmen.')} ${cite('kobak-excess-vocabulary-2025','Kobak et al., 2025')}. ${t('An exploratory study did not find an overall human preference for the conspicuous words it tested.','Eine explorative Studie fand keine allgemeine menschliche Vorliebe für die untersuchten auffälligen Wörter.')} ${cite('juzek-lexical-2025',t('Juzek and Ward, 2025','Juzek und Ward, 2025'))}.</p><p>${t('A rule therefore needs a condition, a reader cost and an exception. Banning a word everywhere would erase useful terminology along with empty phrasing.','Eine Regel braucht deshalb eine Anwendungsbedingung, einen benannten Nachteil für die Leser und eine Ausnahme. Ein pauschales Wortverbot würde neben leeren Formulierungen auch nützliche Fachbegriffe entfernen.')}</p>
<h3>${t('Revision needs an explicit success criterion','Vor der Überarbeitung festlegen, was besser werden soll')}</h3><p>${t('Self-Refine improved its tested tasks, but a reasoning study found that unsupported self-correction could introduce errors. The tasks and feedback conditions differ.','Self-Refine verbesserte die Ergebnisse in den untersuchten Aufgaben. Eine Studie zu Schlussfolgerungsaufgaben zeigte dagegen, dass Selbstkorrektur ohne zusätzliche Rückmeldung Fehler einführen kann. Die Aufgaben und Rückmeldungsbedingungen der Studien unterscheiden sich.')} ${cite('self-refine','Madaan et al., 2023')}; ${cite('self-correction-counterevidence','Huang et al., ICLR 2024')}.</p><p>${t("Our implication is to require a quoted problem and compare the revision with the source. Preserve evidence, qualifications and accepted decisions. Shorter output, a model's approval and a high acceptance rate each leave important questions unanswered.",'Für Voice leiten wir daraus ab: Den beanstandeten Text zitieren und jede Überarbeitung mit der Quelle vergleichen. Belege, sachliche Einschränkungen und akzeptierte Entscheidungen müssen erhalten bleiben. Weder kürzere Antworten noch die Zustimmung eines Modells oder eine hohe Übernahmequote belegen allein eine Verbesserung.')}</p>
<h3>${t('Quality and authorship need different evidence','Textqualität und Urheberschaft getrennt prüfen')}</h3><p>${t('Historical detector studies found sensitivity to language background, generator changes and mixed editing. Their reported rates apply to the tested conditions.','Frühere Studien zu KI-Detektoren zeigten, dass Sprachhintergrund, andere Generatormodelle und die gemeinsame Bearbeitung durch Mensch und KI die Ergebnisse beeinflussen. Die gemeldeten Fehlerraten gelten für die jeweils untersuchten Bedingungen.')} ${cite('liang-detector-bias-2023','Liang et al., 2023')}; ${cite('dugan-raid-2024','RAID, 2024')}; ${cite('zhang-mixset-2024','MixSet, 2024')}.</p><p>${t('Voice returns local writing signals and review rules without an AI-authorship probability. A recorded generation run can document a known contribution; a Git commit by itself does not establish who composed its sentences.','Voice liefert lokale Formulierungshinweise und Review-Regeln, aber keine Wahrscheinlichkeit für KI-Urheberschaft. Ein protokollierter Generierungslauf kann einen bekannten KI-Beitrag dokumentieren. Ein Git-Commit allein belegt nicht, wer die Sätze verfasst hat.')}</p>
</section>
<section id="${prefix}practice"><h2>${t('Practice articles and the “vibe” debate','Praxisartikel und die „Vibe“-Debatte')}</h2><p>${t('These firsthand essays and directories put names to frustrating writing habits. Read them as examples and editorial arguments. Their model labels and proposed remedies rarely come with controlled comparisons.','Diese Erfahrungsberichte und Sammlungen benennen störende Schreibgewohnheiten. Sie liefern Beispiele und redaktionelle Argumente. Die genannten Modelle und Gegenmaßnahmen wurden dabei selten kontrolliert verglichen.')}</p>${researchApplication('practice',locale)}${practice.map(record=>entry(record,locale)).join('')}</section>
<section id="${prefix}studies"><h2>${t('Studies: methods, findings and limits','Studien: Methoden, Ergebnisse und Grenzen')}</h2><p>${t('The collection covers text quality, lexical drift, homogenization, agreeable feedback, online accusations and authorship detection. Each record separates the measured setting from its implication for Voice and names the API functions available today. Preprints are identified in their limits.','Die Sammlung behandelt Textqualität, veränderten Wortgebrauch, sprachliche Vereinheitlichung, übermäßig zustimmendes Feedback, KI-Vorwürfe im Netz und die Erkennung von Urheberschaft. Jeder Eintrag trennt die untersuchten Bedingungen von unserer Folgerung für Voice und nennt die heute verfügbaren API-Funktionen. Bei Preprints weist der Abschnitt zu den Grenzen auf den Veröffentlichungsstatus hin.')}</p>${researchApplication('studies',locale)}${studies.map(record=>entry(record,locale)).join('')}</section>
<section id="${prefix}strategies"><h2>${t('Counter-strategies and their evidence','Gegenstrategien und ihre Belege')}</h2><p>${t('A counter-prompt is an intervention to test. These studies examine training incentives, iterative feedback and human control; none qualifies the current Voice prompts across Claude, Codex and Gemini.','Ob ein Gegen-Prompt hilft, muss geprüft werden. Diese Studien untersuchen Trainingsanreize, wiederholtes Feedback und menschliche Kontrolle. Keine davon belegt die Wirksamkeit der aktuellen Voice-Prompts über Claude, Codex und Gemini hinweg.')}</p>${researchApplication('strategies',locale)}${strategies.map(record=>entry(record,locale)).join('')}
<div class="research-choice"><h3>${t('Compose a small review brief','Den Review-Auftrag eingrenzen')}</h3><p>${t('The current Library combines a selected rule profile with the audience and goal. A host can add supported facts, source text and accepted decisions as separately identified context. The prompt asks for specific findings and up to three warranted alternatives; keeping the text remains an available decision.','Die Library verbindet ein ausgewähltes Regelprofil mit Zielgruppe und Ziel. Die einbindende Anwendung kann belegte Fakten, Quelltext und akzeptierte Entscheidungen als getrennt gekennzeichneten Kontext ergänzen. Der Prompt fordert konkrete Befunde und bis zu drei begründete Alternativen an. Den Text beizubehalten bleibt eine mögliche Entscheidung.')}</p><p><a href="../guides/writing-tools/">${t('Integrate writing tools in your application','Schreibwerkzeuge in die eigene Anwendung einbinden')}</a> · <a href="../guides/writing-rules/">${t('Use the typed API','Die typisierte API verwenden')}</a></p></div>
</section>
<section id="${prefix}libraries"><h2>${t('Libraries and engines','Bibliotheken und Analysewerkzeuge')}</h2><p>${t('Capabilities, licenses and maintenance were checked against project-owned sources on 12 September 2026. The integration assessments below are our technical judgment. This comparison examines documented capabilities. It does not report installed integrations or comparative performance results.','Funktionen, Lizenzen und Projektpflege wurden am 12. September 2026 anhand der Quellen der jeweiligen Projekte geprüft. Die Einschätzungen zur Einbindung in Voice stammen von uns. Der Vergleich beschreibt dokumentierte Fähigkeiten. Die Werkzeuge sind noch nicht in Voice eingebunden; vergleichende Leistungsmessungen liegen nicht vor.')}</p>
${researchApplication('libraries',locale)}<div class="research-table-wrap" tabindex="0" role="region" aria-label="${t('Library execution and language comparison','Vergleich von Ausführung und Sprachabdeckung')}"><table class="research-library-table"><thead><tr><th scope="col">${t('Project','Projekt')}</th><th scope="col">${t('Execution and API','Ausführung und API')}</th><th scope="col">${t('Language coverage','Sprachabdeckung')}</th></tr></thead><tbody>${libraries.map(record=>`<tr><th scope="row"><a href="#${prefix}${e(record.id)}">${e(record.name)}</a></th><td>${e(record.execution)}</td><td>${e(record.languageSupport)}</td></tr>`).join('')}</tbody></table></div>
${libraries.map(record=>library(record,locale)).join('')}
</section>
<section id="${prefix}voice"><h2>${t('How the research becomes a review','Wie die Forschung in ein Review einfließt')}</h2><p>${t("Voice's rule catalogue stores "+catalogue.rules.length+" negative patterns with reader costs, examples, exceptions and counter-prompts. Four profiles select six rules each. The browser's local scanner covers eight rules; it reports exact UTF-16 spans and explicitly identifies rules requiring semantic review.",'Der Voice-Regelkatalog enthält '+catalogue.rules.length+' Negativmuster mit Nachteilen für die Leser, Beispielen, Ausnahmen und Gegen-Prompts. Vier Profile wählen jeweils sechs Regeln aus. Der lokale Scanner der Library deckt acht Regeln ab. Er liefert genaue UTF-16-Textbereiche und benennt die Regeln, die eine inhaltliche Prüfung benötigen.')}</p>
<div class="research-table-wrap" tabindex="0" role="region" aria-label="${t('Review scope and evidence','Review-Umfang und erforderliche Belege')}"><table><thead><tr><th scope="col">${t('Question','Fragestellung')}</th><th scope="col">${t('Evidence to supply','Benötigte Grundlagen')}</th><th scope="col">${t('Current Voice boundary','Aktueller Funktionsumfang')}</th></tr></thead><tbody>
<tr><th scope="row">${t('Does this wording obscure the point?','Erschwert diese Formulierung das Verständnis?')}</th><td>${t('Exact quote, surrounding text, reader task and the relevant rule.','Genaues Zitat, umgebender Text, Anliegen der Leser und zugehörige Regel.')}</td><td>${t('Local candidate signals and composed review prompts are available in the writing-rules package.','Das Paket writing-rules liefert lokale Prüfkandidaten und zusammengestellte Review-Prompts.')}</td></tr>
<tr><th scope="row">${t('Does the whole page serve its goal?','Erfüllt die gesamte Seite ihren Zweck?')}</th><td>${t('Page purpose, audience, complete content, accepted positioning and supporting sources.','Seitenziel, Zielgruppe, vollständiger Inhalt, akzeptierte Positionierung und belegende Quellen.')}</td><td>${t('A host must run and validate a contextual analysis. The local scanner does not assess page strategy.','Die einbindende Anwendung muss eine Kontextanalyse ausführen und prüfen. Der lokale Scanner bewertet keine Seitenstrategie.')}</td></tr>
<tr><th scope="row">${t('Is the project consistent?','Ist das Projekt in sich konsistent?')}</th><td>${t('Selected files at a known revision, terminology, cross-page claims and review decisions.','Ausgewählte Dateien mit bekanntem Versionsstand, Begriffe, seitenübergreifende Aussagen und Review-Entscheidungen.')}</td><td>${t('Git can retain reviewed records. Automated project-wide SEO and visual review are not implemented.','Review-Daten können in Git gespeichert werden. Automatische projektweite Prüfungen von SEO und visuellem Eindruck sind noch nicht implementiert.')}</td></tr>
<tr><th scope="row">${t('Did AI compose this passage?','Hat eine KI diese Textstelle verfasst?')}</th><td>${t('Known generation provenance or a separately qualified attribution method.','Dokumentierte Generierung oder ein gesondert validiertes Verfahren zur Zuordnung.')}</td><td>${t('The package supplies no authorship verdict or probability.','Das Paket liefert weder ein Urteil noch eine Wahrscheinlichkeit zur Urheberschaft.')}</td></tr>
</tbody></table></div>
<p>${t('The rule package and the review UI have separate responsibilities. <code>@voice/writing-rules</code> selects rules, composes prompts and identifies surface cues. <code>@voice/review</code> maps supplied findings onto text. Studio currently runs its existing four local checks; the expanded catalogue is not automatically connected to its backend.','Regelpaket und Review-Oberfläche haben getrennte Aufgaben. <code>@voice/writing-rules</code> wählt Regeln aus, stellt Prompts zusammen und erkennt feste Formulierungsmuster. <code>@voice/review</code> ordnet bereitgestellte Befunde den Textstellen zu. Studio führt derzeit seine vier bestehenden lokalen Prüfungen aus. Der erweiterte Katalog ist noch nicht an das Backend angebunden.')}</p>
<h3>${t('Measure a remedy against preserved intent','Prüfen, ob die Überarbeitung die Aussage erhält')}</h3><p>${t('Our proposed evaluation unit is a source passage plus its purpose, supporting facts and accepted decisions. Compare the unchanged source with revisions from a versioned prompt. Reviewers should assess task completion, factual preservation, unnecessary text and unwanted changes separately. Include legitimate examples of each pattern, German and English material, and human-edited model drafts.','Als Bewertungseinheit schlagen wir eine Textstelle mit ihrem Zweck, belegenden Fakten und akzeptierten Entscheidungen vor. Die unveränderte Quelle wird mit Überarbeitungen aus einem versionierten Prompt verglichen. Bewertende Personen sollten Aufgabenerfüllung, Faktentreue, unnötigen Text und unerwünschte Änderungen getrennt beurteilen. Zum Testmaterial gehören auch sinnvolle Verwendungen der jeweiligen Muster, deutsche und englische Texte sowie menschlich bearbeitete KI-Entwürfe.')}</p><p>${t('These are qualification criteria for future model comparisons. The current tests verify the catalogue, prompt composition, local matching and browser behavior; they do not measure improved writing quality from model use.','Das sind Kriterien für künftige Modellvergleiche. Die aktuellen Tests prüfen Katalog, Prompt-Zusammenstellung, lokale Mustererkennung und Browserverhalten. Sie messen noch keine Verbesserung der Textqualität durch Modelleinsatz.')}</p>
<p><a href="../writing-patterns/">${t('Explore the pattern catalogue','Den Musterkatalog lesen')}</a> · <a href="../studio/">${t('See the review UI','Die Review-Oberfläche ansehen')}</a> · <a href="../guides/ai-text-signals/">${t('Read the detection boundaries','Die Grenzen der Erkennung nachlesen')}</a></p>
</section>
${libraryAnalysis(locale)}
${reviewEconomics(locale)}
<section id="${prefix}sources"><h2>${t('Sources and reusable research data','Quellen und wiederverwendbare Forschungsdaten')}</h2><p>${t('This is a curated collection of '+practice.length+' practice sources, '+studies.length+' studies, '+strategies.length+' strategy studies and '+libraries.length+' tools, selected for writing quality, review decisions and implementation fit. It is not a systematic review or a provider ranking. Source records include the sections read, limitations and related rule IDs; tool records link official documentation, licenses and release evidence.','Die kuratierte Sammlung umfasst '+practice.length+' Praxisquellen, '+studies.length+' Studien, '+strategies.length+' Studien zu Gegenstrategien und '+libraries.length+' Werkzeuge. Die Auswahl richtet sich nach ihrem Beitrag zu Textqualität, Review-Entscheidungen und technischer Umsetzung. Sie ist keine systematische Literaturübersicht und keine Rangliste von Anbietern. Die Einträge nennen gelesene Abschnitte, Grenzen und zugehörige Regel-IDs. Bei Werkzeugen verweisen sie auf offizielle Dokumentation, Lizenzen und Veröffentlichungsnachweise.')}</p><p>${t('The JSON records are maintained in Git under <code>website/research/</code>. They contain original summaries and links; third-party prompts, papers and library code are not bundled. Open a record set to inspect or reuse the structured data.','Die JSON-Datensätze werden in Git unter <code>website/research/</code> gepflegt; die deutschen Fassungen liegen unter <code>website/research/de/</code>. Sie enthalten eigene Zusammenfassungen und Links. Fremde Prompts, Fachartikel und Bibliothekscode werden nicht mitgeliefert. Die Datensätze lassen sich öffnen und als strukturierte Daten weiterverwenden.')}</p><div class="research-downloads">${Object.keys(researchGroups).map(key=>`<a href="../sources/research/${de?'de/':''}${key}.json">${e(de?{practice:'Praxisartikel',studies:'Studien',strategies:'Gegenstrategien',libraries:'Bibliotheken'}[key]:key[0].toUpperCase()+key.slice(1))} JSON</a>`).join('')}</div>
<details class="research-entry" id="${prefix}source-index"><summary>${t('Source index','Quellenverzeichnis')}<span>${t('Original articles, papers and repositories','Originalartikel, Studien und Repositories')}</span></summary><ol class="research-source-list">${localizedRecords.map(record=>`<li><a href="${e(record.url)}">${e(record.title||record.name)}</a>${record.authors?' — '+e(authors(record)):''}${record.date?' ('+e(record.date)+')':''} · <a href="#${prefix}${e(record.id)}">${t('Research note','Analyse zur Quelle')}</a></li>`).join('')}</ol></details>
</section></section>`;
}
