import {reviewEconomics} from './review-economics.mjs';
import practice from './research/practice.json' with {type:'json'};
import studies from './research/studies.json' with {type:'json'};
import strategies from './research/strategies.json' with {type:'json'};
import libraries from './research/libraries.json' with {type:'json'};
import catalogue from '../packages/writing-rules/src/catalogue.json' with {type:'json'};
import {escape as e} from './template.mjs';

export const researchGroups={practice,studies,strategies,libraries};
const records=Object.values(researchGroups).flat();
const ids=new Set(),ruleIds=new Set(catalogue.rules.map(r=>r.id));
for(const record of records){
  if(!record.id||ids.has(record.id)||!/^https:\/\//.test(record.url)||!record.relatedRuleIds.every(id=>ruleIds.has(id)))throw new Error('Invalid research record: '+record.id);
  ids.add(record.id);
}
const rules=record=>`<p class="research-rules">Related patterns: ${record.relatedRuleIds.map(id=>`<a href="../writing-patterns/#en-${e(id)}">${e(catalogue.rules.find(r=>r.id===id).antiPattern.name.en)}</a>`).join(' · ')}</p>`;
const paragraphs=items=>items.map(item=>`<p>${e(item)}</p>`).join('');
const authors=record=>record.authors.length>2?record.authors.slice(0,2).join(', ')+' et al.':record.authors.join(', ');
const field=(name,text)=>`<dt>${name}</dt><dd>${Array.isArray(text)?paragraphs(text):e(text)}</dd>`;
const cite=(id,label)=>{const record=records.find(r=>r.id===id);if(!record)throw new Error('Unknown research citation: '+id);return `<a href="${e(record.url)}">${e(label)}</a>`};
const sourceMeta=record=>`<p class="research-meta">${e(authors(record))} · ${e(record.date||'Undated; accessed 12 September 2026')} · <a href="${e(record.url)}">Original source</a></p>`;
const apiReference={
  getWritingRule:'../guides/writing-rules/',selectWritingRules:'../guides/writing-rules/',
  composeWritingReviewPrompt:'../guides/writing-rules/',findWritingSignals:'../guides/writing-rules/',
  mountVoiceReview:'../guides/library/'
};
function apiUse(record){
  const use=record.apiUse;
  if(!use||!use.availableNow.length||use.availableNow.some(api=>!Object.hasOwn(apiReference,api.symbol)))throw new Error('Missing or invalid research API connection: '+record.id);
  return `<section class="research-api" aria-label="API connection"><h3>Use with Voice</h3><p>${e(use.currentUse)}</p><ul>${use.availableNow.map(api=>`<li><a href="${apiReference[api.symbol]}"><code>${e(api.symbol)}</code></a> — ${e(api.purpose)}</li>`).join('')}</ul><p><strong>What is missing:</strong> ${e(use.missingCapability)}</p></section>`;
}
function entry(record){
  const isStudy=record.kind==='study',isStrategy=record.kind==='strategy-evidence';
  const brief=isStudy?record.question:isStrategy?record.application.replace(/^Voice implication: /,''):record.voiceImplication;
  return `<details class="research-entry" id="${e(record.id)}"><summary>${e(record.title)}<span>${e(brief)}</span></summary><div class="research-detail">${sourceMeta(record)}<dl>${isStudy?field('Method',record.method)+field('Findings',record.findings)+field('Limits',record.limitations):isStrategy?field('Method',record.method)+field('Finding',record.finding)+field('Limits',record.limits):field('Observation',record.observation)+field('Limits',record.limits)}${isStudy?field('Implication for Voice',record.voiceImplication):''}</dl>${apiUse(record)}${rules(record)}<p class="research-meta">${e(record.readingDepth)}</p></div></details>`;
}
function library(record){
  return `<details class="research-entry" id="${e(record.id)}"><summary>${e(record.name)}<span>${e(record.voiceFit.replace(/^Assessment: /,''))}</span></summary><div class="research-detail"><p><a href="${e(record.url)}">Official repository</a> · <a href="${e(record.license.url)}">${e(record.license.id)} license</a></p><dl>${field('Execution',record.execution)}${field('Languages',record.languageSupport)}${field('Capabilities',record.capabilities)}${field('Limits',record.limits)}${field('Maintenance snapshot · '+record.maintenance.checkedAt,record.maintenance.observation)}</dl>${apiUse(record)}${rules(record)}<ul>${record.refs.map(ref=>`<li><a href="${e(ref.url)}">${e(ref.title)}</a></li>`).join('')}</ul></div></details>`;
}
export function researchIntro(locale){
  const de=locale==='de';
  return `<header class="research-heading"><p class="research-date">${de?'Voice Research · 12. September 2026':'Voice Research · 12 September 2026'}</p><h1>${de?'Texte, die man gern liest.':'Writing worth reading.'}</h1><p class="lead">${de?'Wie Texte nützlich werden und Freude am Lesen machen. Forschung, konkrete Regeln und ihre Anwendung mit Voice.':'Research on useful, engaging writing and how to put it into practice with Voice.'}</p><p><a href="../writing-patterns/">${de?'Negativmuster und Gegen-Prompts ausprobieren':'Try the anti-patterns and counter-prompts'} ↗</a></p><nav class="research-nav" aria-label="${de?'Forschungsthemen':'Research topics'}">${[['findings','Findings','Befunde'],['practice','Practice articles','Praxisartikel'],['studies','Studies','Studien'],['strategies','Counter-strategies','Gegenstrategien'],['libraries','Libraries','Libraries'],['voice','In Voice','In Voice'],['economics','Review cost','Review-Kosten'],['sources','Sources & data','Quellen & Daten']].map(([id,en,dt])=>`<a href="#${id}">${de?dt:en}</a>`).join('')}</nav><p class="research-language">${de?'Die vertiefenden Analysen und Quellenkommentare stehen auf Englisch. Beispiele und Gegen-Prompts im Musterkatalog sind deutsch und englisch verfügbar.':'Research notes are in English. Pattern examples and counter-prompts are available in English and German.'}</p></header>`;
}
export const researchContent=`<section class="research-content" lang="en" aria-label="Research analysis and source collection">
<section id="findings" class="research-findings"><h2>What the evidence changes</h2>
<h3>Review the reader's problem</h3><p>Relevance, information density and tone helped explain expert judgments in <em>Measuring AI ‘Slop’</em>. Agreement was stronger on problematic passages than on a binary label. ${cite('shaib-slop-2025','Shaib et al., preprint, revised 2026')}.</p><p>For Voice, this supports a contextual question: which passage prevents the reader from understanding, deciding or acting? Word matches can locate candidates; the page's purpose determines whether they need changing.</p>
<h3>Better individual texts can still become more alike</h3><p>In a randomized short-story experiment, AI ideas improved ratings while assisted stories became more similar. This is evidence for assessing usefulness and distinctiveness separately. ${cite('doshi-creativity-diversity-2024','Doshi and Hauser, 2024')}.</p><p>In a contextual review, compare repeated framing across a page and across proposed alternatives. Three rewrites that merely swap synonyms offer little choice. A deliberate rhythm or an accepted headline can remain effective.</p>
<h3>A familiar word is a clue with a narrow scope</h3><p>Corpus research detects abrupt vocabulary shifts; it cannot identify the origin of an individual passage. ${cite('kobak-excess-vocabulary-2025','Kobak et al., 2025')}. An exploratory study did not find an overall human preference for the conspicuous words it tested. ${cite('juzek-lexical-2025','Juzek and Ward, 2025')}.</p><p>A rule therefore needs a condition, a reader cost and an exception. Banning a word everywhere would erase useful terminology along with empty phrasing.</p>
<h3>Revision needs an explicit success criterion</h3><p>Self-Refine improved its tested tasks, but a reasoning study found that unsupported self-correction could introduce errors. The tasks and feedback conditions differ. ${cite('self-refine','Madaan et al., 2023')}; ${cite('self-correction-counterevidence','Huang et al., ICLR 2024')}.</p><p>Our implication is to require a quoted problem and compare the revision with the source. Preserve evidence, qualifications and accepted decisions. Shorter output, a model's approval and a high acceptance rate each leave important questions unanswered.</p>
<h3>Quality and authorship need different evidence</h3><p>Historical detector studies found sensitivity to language background, generator changes and mixed editing. Their reported rates apply to the tested conditions. ${cite('liang-detector-bias-2023','Liang et al., 2023')}; ${cite('dugan-raid-2024','RAID, 2024')}; ${cite('zhang-mixset-2024','MixSet, 2024')}.</p><p>Voice returns local writing signals and review rules without an AI-authorship probability. A recorded generation run can document a known contribution; a Git commit by itself does not establish who composed its sentences.</p>
</section>
<section id="practice"><h2>Practice articles and the “vibe” debate</h2><p>These firsthand essays and directories put names to frustrating writing habits. Read them as examples and editorial arguments. Their model labels and proposed remedies rarely come with controlled comparisons.</p>${practice.map(entry).join('')}</section>
<section id="studies"><h2>Studies: methods, findings and limits</h2><p>The collection covers text quality, lexical drift, homogenization, agreeable feedback, online accusations and authorship detection. Each record separates the measured setting from its implication for Voice and names the API functions available today. Preprints are identified in their limits.</p>${studies.map(entry).join('')}</section>
<section id="strategies"><h2>Counter-strategies and their evidence</h2><p>A counter-prompt is an intervention to test. These studies examine training incentives, iterative feedback and human control; none qualifies the current Voice prompts across Claude, Codex and Gemini.</p>${strategies.map(entry).join('')}
<div class="research-choice"><h3>Compose a small review brief</h3><p>The current Library combines a selected rule profile with the audience and goal. A host can add supported facts, source text and accepted decisions as separately identified context. The prompt asks for specific findings and up to three warranted alternatives; keeping the text remains an available decision.</p><p><a href="../writing-patterns/#en-playground">Try local signals and prompt composition</a> · <a href="../guides/writing-rules/">Use the typed API</a></p></div>
</section>
<section id="libraries"><h2>Libraries and engines</h2><p>Capabilities, licenses and maintenance were checked against project-owned sources on 12 September 2026. The integration assessments below are our technical judgment. This comparison examines documented capabilities. It does not report installed integrations or comparative performance results.</p>
<div class="research-table-wrap" tabindex="0" role="region" aria-label="Library execution and language comparison"><table class="research-library-table"><thead><tr><th scope="col">Project</th><th scope="col">Execution and API</th><th scope="col">Language coverage</th></tr></thead><tbody>${libraries.map(record=>`<tr><th scope="row"><a href="#${e(record.id)}">${e(record.name)}</a></th><td>${e(record.execution)}</td><td>${e(record.languageSupport)}</td></tr>`).join('')}</tbody></table></div>
${libraries.map(library).join('')}
</section>
<section id="voice"><h2>How the research becomes a review</h2><p>Voice's rule catalogue stores ${catalogue.rules.length} negative patterns with reader costs, examples, exceptions and counter-prompts. Four profiles select six rules each. The browser's local scanner covers eight rules; it reports exact UTF-16 spans and explicitly identifies rules requiring semantic review.</p>
<div class="research-table-wrap" tabindex="0" role="region" aria-label="Review scope and evidence"><table><thead><tr><th scope="col">Question</th><th scope="col">Evidence to supply</th><th scope="col">Current Voice boundary</th></tr></thead><tbody>
<tr><th scope="row">Does this wording obscure the point?</th><td>Exact quote, surrounding text, reader task and the relevant rule.</td><td>Local candidate signals and composed review prompts are available in the writing-rules package.</td></tr>
<tr><th scope="row">Does the whole page serve its goal?</th><td>Page purpose, audience, complete content, accepted positioning and supporting sources.</td><td>A host must run and validate a contextual analysis. The local scanner does not assess page strategy.</td></tr>
<tr><th scope="row">Is the project consistent?</th><td>Selected files at a known revision, terminology, cross-page claims and review decisions.</td><td>Git can retain reviewed records. Automated project-wide SEO and visual review are not implemented.</td></tr>
<tr><th scope="row">Did AI compose this passage?</th><td>Known generation provenance or a separately qualified attribution method.</td><td>The package supplies no authorship verdict or probability.</td></tr>
</tbody></table></div>
<p>The rule package and the review UI have separate responsibilities. <code>@voice/writing-rules</code> selects rules, composes prompts and identifies surface cues. <code>@voice/review</code> maps supplied findings onto text. Studio currently runs its existing four local checks; the expanded catalogue is not automatically connected to its backend.</p>
<h3>Measure a remedy against preserved intent</h3><p>Our proposed evaluation unit is a source passage plus its purpose, supporting facts and accepted decisions. Compare the unchanged source with revisions from a versioned prompt. Reviewers should assess task completion, factual preservation, unnecessary text and unwanted changes separately. Include legitimate examples of each pattern, German and English material, and human-edited model drafts.</p><p>These are qualification criteria for future model comparisons. The current tests verify the catalogue, prompt composition, local matching and browser behavior; they do not measure improved writing quality from model use.</p>
<p><a href="../writing-patterns/">Explore the pattern catalogue</a> · <a href="../studio/">See the review UI</a> · <a href="../guides/ai-text-signals/">Read the detection boundaries</a></p>
</section>
${reviewEconomics()}
<section id="sources"><h2>Sources and reusable research data</h2><p>This is a curated collection of ${practice.length} practice sources, ${studies.length} studies, ${strategies.length} strategy studies and ${libraries.length} tools, selected for writing quality, review decisions and implementation fit. It is not a systematic review or a provider ranking. Source records include the sections read, limitations and related rule IDs; tool records link official documentation, licenses and release evidence.</p><p>The JSON records are maintained in Git under <code>website/research/</code>. They contain original summaries and links; third-party prompts, papers and library code are not bundled. Open a record set to inspect or reuse the structured data.</p><div class="research-downloads">${Object.keys(researchGroups).map(key=>`<a href="../sources/research/${key}.json">${key[0].toUpperCase()+key.slice(1)} JSON</a>`).join('')}</div>
<details class="research-entry" id="source-index"><summary>Source index<span>Original articles, papers and repositories</span></summary><ol class="research-source-list">${records.map(record=>`<li><a href="${e(record.url)}">${e(record.title||record.name)}</a>${record.authors?' — '+e(authors(record)):''}${record.date?' ('+e(record.date)+')':''} · <a href="#${e(record.id)}">Research note</a></li>`).join('')}</ol></details>
</section></section>`;
