import {escape} from './template.mjs';
import studioCopy from './content/studio.json' with {type:'json'};
import {libraryIntroduction,toolExample} from './tooling-library.mjs';
import {researchIntro,researchContent} from './research.mjs';
import {writingPatterns} from './writing-patterns.mjs';
import {studioTour} from './studio-tour.mjs';
import {docsIndex} from './docs-index.mjs';
export const pages = [
  {slug:'research',title:'Voice Research · AI writing patterns, evidence and libraries',description:'Explore firsthand writing critiques, empirical studies, counter-strategies and existing libraries, with methods, limitations and implications for Voice.',en:researchIntro('en')+researchContent('en'),de:researchIntro('de')+researchContent('de')},
  {slug:'writing-patterns',title:'Voice · AI writing anti-patterns and counter-prompts',description:'Explore concrete AI writing anti-patterns with English and German examples, reader costs, counter-prompts, exceptions and reusable Library rules.',en:writingPatterns('en'),de:writingPatterns('de')},
  { slug: "", title: "Voice · A review UI and a typed Library for your source", description: "Voice Studio UI and the framework-independent review Library: work with Git repositories or ordinary folders, inspect text in context and keep source changes reviewable.",
    en: `
<section class="hero"><p class="eyebrow">Voice · Studio + Libraries</p><h1>Review the words.<br><em>Keep the intent.</em></h1><p class="lead">A review UI for your team. Two typed libraries for your agents and applications. Work in your Git repository, with source files and review records in project folders. Connect the words you see to the file they came from.</p><div class="actions"><a class="button" href="studio/">Explore the Studio UI</a><a class="button secondary" href="library/">Use the Library</a></div><p class="status">Git-backed · Local source files · English and German UI</p></section>
<section class="intro"><p class="eyebrow">Choose your entry point</p><h2>The same review data.<br>In Studio or your own UI.</h2></section>
<div class="product-pair">
  <section class="product-pane"><div class="product-body"><p class="eyebrow">Voice Studio · User interface</p><h2>See the page and its source.</h2><p>Open the local website, review a passage and keep it or compare alternatives. File, source version and optional Git context stay attached to the work.</p></div><figure class="product-visual"><a href="assets/studio-review.png" target="_blank" rel="noopener" title="Open full-size Studio screenshot"><img src="assets/studio-review.png" alt="Actual local Voice Studio interface showing a website preview alongside its review panel" width="1180" height="820" loading="eager"></a><figcaption>Actual local Studio session reviewing the Agent Studio website.</figcaption></figure><div class="product-body"><a href="studio/">Explore the Studio workflow ↗</a></div></section>
  <section class="product-pane"><div class="product-body"><p class="eyebrow">Agent tools + HTML · Two libraries</p><h2>Build review into your application.</h2><p>Use <code>@voice/writing-rules</code> for rule knowledge, review prompts and LLM tools. Use <code>@voice/review</code> to visualize findings in HTML. Both packages support TypeScript and JavaScript with IntelliSense.</p></div><div class="product-code"><pre><code class="language-typescript">${toolExample}</code></pre><p>Local tool call · The host registers schemas and runs its model.</p></div><div class="product-body"><a href="library/">Explore both libraries and typed examples ↗</a></div></section>
</div>
<section class="prose home-git"><h2>Review in your Git repository.</h2><p>Your source stays in the checkout. Studio shows the branch, commit and local changes, and stores feedback, tasks and decisions under <code>.voice-lint/</code> in the project. Each proposal refers to a specific source version.</p><p>Review the source diff, verify the rendered page and choose the files for your commit. Run records can contain source context and model output; inspect them before sharing.</p><p>You can also open a source folder without Git. Source hashes protect reviews when the file changes.</p><a href="guides/workflow/#saved-tasks-and-decisions">See the file tree and saved JSON ↗</a></section>
<section class="flow"><h2>From a passage to a decision</h2><ol><li><strong>Locate</strong><span>Connect rendered text to its file and version.</span></li><li><strong>Review</strong><span>Read the reason in the page’s context.</span></li><li><strong>Decide</strong><span>Keep it or choose a proposed change.</span></li><li><strong>Verify</strong><span>Inspect the diff and the rendered result.</span></li></ol></section>
<section class="feature"><h2>Recognize AI writing anti-patterns.</h2><p>“Not X, but Y.” Empty importance prefaces. Development history in public documentation. Inspect the patterns, understand their reader cost and use a counter-prompt with your model.</p><a href="writing-patterns/">Explore AI writing anti-patterns ↗</a><p><a href="research/">Read the research: practice articles, studies and libraries ↗</a></p></section>
<section class="note"><h2>Available from the local workspace</h2><p>Voice Studio is a supervised local preview. The packages supply writing tools and HTML annotations, selection and an explicit live-page bridge. Build the packages in the local checkout and start Studio on your machine. The current preview supports supervised file reviews.</p><a href="docs/">Read the docs ↗</a></section>`,
    de: `
<section class="hero"><p class="eyebrow">Voice · Studio + Libraries</p><h1>Texte prüfen.<br><em>Absicht bewahren.</em></h1><p class="lead">Eine Review-Oberfläche für dein Team. Zwei typisierte Libraries für Agenten und Anwendungen. Arbeite in deinem Git-Repository, mit Quelldateien und Review-Daten in Projektordnern. Verbinde den sichtbaren Text mit seiner Datei.</p><div class="actions"><a class="button" href="studio/">Studio-Oberfläche ansehen</a><a class="button secondary" href="library/">Library verwenden</a></div><p class="status">Git-basiert · Lokale Quelldateien · Englische und deutsche Oberfläche</p></section>
<section class="intro"><p class="eyebrow">Dein Einstieg</p><h2>Dieselben Review-Daten.<br>Im Studio oder in deiner UI.</h2></section>
<div class="product-pair">
  <section class="product-pane"><div class="product-body"><p class="eyebrow">Voice Studio · Benutzeroberfläche</p><h2>Seite und Quelle zusammen sehen.</h2><p>Die lokale Website öffnen, eine Passage prüfen und beibehalten oder Alternativen vergleichen. Datei, Quellversion und optionaler Git-Bezug bleiben mit der Arbeit verbunden.</p></div><figure class="product-visual"><a href="assets/studio-review.png" target="_blank" rel="noopener" title="Open full-size Studio screenshot"><img src="assets/studio-review.png" alt="Echte lokale Voice-Studio-Oberfläche mit Website-Vorschau und geöffnetem Review-Panel" width="1180" height="820" loading="eager"></a><figcaption>Echte lokale Studio-Sitzung beim Review der Agent-Studio-Website.</figcaption></figure><div class="product-body"><a href="studio/">Den Studio-Ablauf ansehen ↗</a></div></section>
  <section class="product-pane"><div class="product-body"><p class="eyebrow">Agent-Tools + HTML · Zwei Libraries</p><h2>Review in die eigene Anwendung einbauen.</h2><p><code>@voice/writing-rules</code> liefert Regelwissen, Prüf-Prompts und LLM-Tools. <code>@voice/review</code> visualisiert Befunde im HTML. Beide Pakete unterstützen TypeScript und JavaScript mit IntelliSense.</p></div><div class="product-code"><pre><code class="language-typescript">${toolExample}</code></pre><p>Lokaler Tool-Aufruf · Die Anwendung registriert Schemas und führt ihr Modell aus.</p></div><div class="product-body"><a href="library/">Beide Libraries und typisierte Beispiele ansehen ↗</a></div></section>
</div>
<section class="prose home-git"><h2>Review in deinem Git-Repository.</h2><p>Deine Quelle bleibt im Checkout. Studio zeigt Branch, Commit und lokale Änderungen und speichert Feedback, Tasks und Entscheidungen unter <code>.voice-lint/</code> im Projekt. Jeder Vorschlag gehört zu einer bestimmten Quellversion.</p><p>Prüfe den Quelldiff und die gerenderte Seite und wähle die Dateien für deinen Commit. Laufdaten können Quellkontext und Modellausgaben enthalten; prüfe sie vor dem Teilen.</p><p>Du kannst auch einen Quellordner ohne Git öffnen. Quellhashes sichern Reviews ab, wenn sich die Datei ändert.</p><a href="guides/workflow/#saved-tasks-and-decisions">Dateibaum und gespeichertes JSON ansehen ↗</a></section>
<section class="flow"><h2>Von der Textstelle zur Entscheidung</h2><ol><li><strong>Zuordnen</strong><span>Sichtbaren Text mit Datei und Version verbinden.</span></li><li><strong>Prüfen</strong><span>Die Begründung im Seitenkontext lesen.</span></li><li><strong>Entscheiden</strong><span>Beibehalten oder einen Vorschlag auswählen.</span></li><li><strong>Verifizieren</strong><span>Diff und gerendertes Ergebnis prüfen.</span></li></ol></section>
<section class="feature"><h2>KI-Negativmuster erkennen.</h2><p>„Nicht X, sondern Y.“ Leere Wichtigkeitsformeln. Entwicklungsgeschichte in öffentlicher Doku. Sieh dir die Negativmuster an, prüfe ihr Leserproblem und nutze den passenden Gegen-Prompt.</p><a href="writing-patterns/">KI-Negativmuster und Gegen-Prompts ansehen ↗</a><p><a href="research/">Forschung: Praxisartikel, Studien und Libraries ↗</a></p></section>
<section class="note"><h2>Aus dem lokalen Workspace nutzbar</h2><p>Voice Studio ist eine betreute lokale Preview. Die Pakete liefern Schreib-Tools sowie HTML-Markierungen, Textauswahl und eine ausdrücklich aktivierte Live-Bridge. Baue die Pakete im lokalen Checkout und starte Studio auf deinem Rechner. Die aktuelle Preview unterstützt betreute Datei-Reviews.</p><a href="docs/">Doku lesen ↗</a></section>`
  },
  { slug: "studio", title: "Voice Studio · Review text on your website", description: "Start the local Voice Studio app and learn how selection, keep decisions, alternatives and source proposals work.",
    en: `<header class="page-heading"><p class="eyebrow">${escape(studioCopy.en.eyebrow)}</p><h1>${escape(studioCopy.en.title)}</h1><p class="lead">${escape(studioCopy.en.lead)}</p></header>${studioTour("en")}
<div class="grid"><section class="card"><h2>Start locally</h2><p>From the Voice Studio workspace, run npm start. Open the app, enter the backend’s pairing code and choose whether to remember this browser for seven days. Requires Node.js 24, .NET SDK 10 and Bash.</p><a href="http://127.0.0.1:5188/">Open local app <span aria-hidden="true">↗</span></a></section><section class="card"><h2>Read the workflow</h2><p>Register the actual source folder and its local development URL. An opt-in bridge maps supported text to the original file.</p><a href="../guides/workflow/">Read the workflow <span aria-hidden="true">↗</span></a></section></div><pre><code>cd voice-studio
npm start
# App: http://127.0.0.1:5188/</code></pre>
<section class="prose"><h2>Keep or change a passage.</h2><p>Select a mapped passage. Choose <strong>Keep as written</strong> to retain a decision for that source version. A reason is optional. Existing rule suggestions can be inspected immediately; generating up to three distinct alternatives starts an explicitly configured model route.</p><p>Selecting an alternative prepares a source diff. Applying the diff is a separate action. Your own feedback and replacement text remain optional. Current local rules are advisory and are not suppressed by a keep decision.</p><h2>Return without entering the code again.</h2><p>Remember this browser for seven days keeps access across reloads and backend restarts on the same Studio origin. The period is fixed and does not extend with every visit. Sign out revokes that browser’s remembered access; another browser stays independent. The code is needed again after expiry or sign-out. Backend credentials stay out of the reviewed website.</p><h2>Give the page room.</h2><p>Use Full, Compact or Website focus navigation. In focus mode the page fills the viewport; navigation and review open as overlays. English is the default, with a saved German language option. Switching UI language does not translate your source or model output.</p><h2>Know which source you see.</h2><p>The current file, source version and optional Git branch/commit identify the local working copy. A saved task result is historical evidence, not the current Git diff. The online site may use a different revision.</p><h2>Operating scope</h2><p>The preview supports explicitly mapped local HTML, a Markdown subset and TypeScript prose literals. Dynamic or ambiguous text stays unassigned. No model runs merely because a page opens. Generated alternatives require host configuration; there is no default model route.</p></section>`,
    de: `<header class="page-heading"><p class="eyebrow">${escape(studioCopy.de.eyebrow)}</p><h1>${escape(studioCopy.de.title)}</h1><p class="lead">${escape(studioCopy.de.lead)}</p></header>${studioTour("de")}<div class="grid"><section class="card"><h2>Lokal starten</h2><p>Im Voice-Studio-Workspace npm start ausführen. In der App den Verbindungscode des Backends eingeben und den Browser bei Bedarf sieben Tage angemeldet lassen. Benötigt Node.js 24, .NET SDK 10 und Bash.</p><a href="http://127.0.0.1:5188/">Lokale App öffnen <span aria-hidden="true">↗</span></a></section><section class="card"><h2>Ablauf verstehen</h2><p>Den tatsächlichen Quellordner und seine lokale Entwicklungs-URL registrieren. Eine ausdrücklich aktivierte Bridge ordnet unterstützte Texte der Originaldatei zu.</p><a href="../guides/workflow/">Ablauf und Schnittstellen <span aria-hidden="true">↗</span></a></section></div><pre><code>cd voice-studio
npm start
# App: http://127.0.0.1:5188/</code></pre><section class="prose"><h2>Eine Passage beibehalten oder ändern.</h2><p>Eine zugeordnete Passage auswählen. <strong>So beibehalten</strong> speichert die Entscheidung für diese Quellversion. Die Begründung ist optional. Vorhandene Regelvorschläge lassen sich direkt prüfen; bis zu drei verschiedene Alternativen entstehen über einen ausdrücklich gestarteten, konfigurierten Modellaufruf.</p><p>Die Auswahl einer Alternative bereitet einen Quelldiff vor. Die Übernahme ist eine eigene Aktion. Eigenes Feedback und eine eigene Formulierung bleiben optional. Lokale Regeln beraten weiterhin; eine Beibehalten-Entscheidung schaltet sie nicht ab.</p><h2>Ohne erneute Codeeingabe zurückkehren.</h2><p>„Diesen Browser 7 Tage merken“ erhält den Zugang bei Neuladen und Backend-Neustart auf demselben Studio-Origin. Die Frist ist fest und verlängert sich nicht mit jedem Besuch. „Abmelden“ widerruft den gespeicherten Zugang dieses Browsers; andere Browser bleiben unabhängig. Nach Ablauf oder Abmeldung ist der Code erneut nötig. Backend-Zugangsdaten gelangen nicht in die geprüfte Website.</p><h2>Der Seite Platz geben.</h2><p>Die Navigation bietet Vollständig, Kompakt und Website-Fokus. Im Fokus füllt die Seite den Bildschirm; Navigation und Review öffnen als Overlays. Englisch ist voreingestellt, Deutsch lässt sich dauerhaft wählen. Ein Sprachwechsel übersetzt weder die Quelle noch Modellausgaben.</p><h2>Den Quellstand erkennen.</h2><p>Datei, Quellversion und optional Git-Branch und Commit zeigen die lokale Arbeitskopie. Gespeicherte Task-Ergebnisse sind historische Nachweise und kein aktueller Git-Diff. Die Online-Seite kann einen anderen Stand verwenden.</p><h2>Einsatzbereich</h2><p>Die Preview unterstützt explizit zugeordnetes lokales HTML, eine Markdown-Teilmenge und TypeScript-Textliterale. Dynamische oder mehrdeutige Texte bleiben unzugeordnet. Das Öffnen einer Seite startet kein Modell. Generierte Alternativen benötigen eine konfigurierte Modellroute; es gibt keine Vorgabe.</p></section>`
  },
  { slug: "library", title: "Voice libraries · Agent tooling and HTML review", description: "Two typed packages: writing rules and LLM tools, plus framework-independent HTML annotations and text selection.",
    en: `${libraryIntroduction("en")}<section class="prose" id="html-review"><h2>Try the HTML library</h2><p>The example below uses the shipped browser bundle. The underline is a supplied example finding, not an analyzer verdict. Select text to inspect its exact quote and UTF-16 span. Nothing is saved or sent to a model.</p></section><div data-demo-slot></div><section class="prose"><h2>What the package does</h2><p><code>mountVoiceReview</code> draws supplied findings and feedback using text-range geometry. It preserves native selection and page interaction. Explicit unit IDs and exact text matches prevent ambiguous anchors from silently pointing elsewhere. Hosts supply an accessible findings list and persistence callbacks.</p><pre><code class="language-typescript">import { mountVoiceReview, type TextUnit }
  from '@voice/review';

export function review(root: HTMLElement) {
  const text = 'Clear copy.';
  root.textContent = text;
  root.dataset.voiceUnit = 'intro';
  const unit: TextUnit = {
    id: 'intro', text, kind: 'paragraph', language: 'en',
    sourceSpan: { start: 0, end: text.length, encoding: 'utf16' }
  };
  const controller = mountVoiceReview({
    root, units: [unit], findings: [], feedback: [],
    onSelect: selection =&gt; console.info(selection.quote)
  });
  return () =&gt; controller.dispose();
}</code></pre><p>Consume the built ESM package in a workspace or copy <code>voice-review.js</code> to local assets. It has no Angular runtime dependency and is not published to npm.</p><h2>TypeScript and JavaScript IntelliSense</h2><p>The public ESM entry ships declarations and JSDoc. Editors using TypeScript’s language service can complete <code>update</code>, <code>selectFinding</code>, <code>getDiagnostics</code> and <code>dispose</code>; selection callbacks infer <code>unitId</code>, <code>quote</code>, <code>start</code> and <code>end</code>. Plain JavaScript uses <code>// @ts-check</code> and JSDoc type imports. The standalone browser global also has a type-only reference.</p><p>The tests compile isolated consumers against the distributed declarations and verify actual language-service completions and hover text. They do not automate the VS Code interface.</p><p><a href="../guides/library-types/">Copy typed examples and inspect the contract</a></p><h2>Connect your AI or agent workflow</h2><p>Your host runs the analysis and validates its output. Convert code-point offsets to UTF-16, check unit identity and the exact quote, and retain the source version before supplying findings. The Library renders those findings; your backend owns credentials, durable decisions, proposals and source writes. The live bridge only exchanges review messages with its configured Studio parent or opener.</p><p><a href="../guides/agent-integration/">Agent integration and result boundaries</a> · <a href="../guides/runner-integration/">Studio’s Runner adapter</a></p><h2>Compose your review rules</h2><p><code>@voice/writing-rules</code> supplies a versioned rule catalogue, review profiles and prompt composition. Local surface checks return candidate passages for human review. Your host runs any model analysis and validates the returned findings.</p><p><a href="../writing-patterns/">Explore the patterns and prompts</a> · <a href="../guides/writing-rules/">Use the writing-rules package</a></p><p><a href="../guides/library/">Full library integration guide</a> · <a href="../guides/live-bridge/">Live bridge protocol</a> · <a href="../docs/">Docs</a></p></section>`,
    de: `${libraryIntroduction("de")}<section class="prose" id="html-review"><h2>Die echte Library ausprobieren</h2><p>Das Beispiel verwendet das gebaute Browser-Bundle. Die Unterstreichung ist ein vorgegebener Beispielbefund, kein Analyzer-Urteil. Eine Textauswahl zeigt das genaue Zitat und seinen UTF-16-Bereich. Es wird nichts gespeichert und kein Modell aufgerufen.</p></section><div data-demo-slot></div><section class="prose"><h2>Was das Paket macht</h2><p><code>mountVoiceReview</code> zeichnet übergebene Befunde und Feedback anhand von Textbereichen. Die normale Textauswahl und Seitenbedienung bleiben erhalten. Explizite Text-IDs und exakte Vergleiche verhindern stille Fehlzuordnungen. Die Anwendung liefert eine zugängliche Befundliste und Speicherfunktionen.</p><pre><code class="language-typescript">import { mountVoiceReview, type TextUnit }
  from '@voice/review';

export function review(root: HTMLElement) {
  const text = 'Clear copy.';
  root.textContent = text;
  root.dataset.voiceUnit = 'intro';
  const unit: TextUnit = {
    id: 'intro', text, kind: 'paragraph', language: 'en',
    sourceSpan: { start: 0, end: text.length, encoding: 'utf16' }
  };
  const controller = mountVoiceReview({
    root, units: [unit], findings: [], feedback: [],
    onSelect: selection =&gt; console.info(selection.quote)
  });
  return () =&gt; controller.dispose();
}</code></pre><p>Das ESM-Paket im Workspace verwenden oder <code>voice-review.js</code> in lokale Assets kopieren. Die Library benötigt keine Angular-Laufzeit und wurde nicht auf npm veröffentlicht.</p><h2>IntelliSense für TypeScript und JavaScript</h2><p>Der öffentliche ESM-Einstieg liefert Deklarationen und JSDoc. Editoren mit TypeScript Language Service ergänzen <code>update</code>, <code>selectFinding</code>, <code>getDiagnostics</code> und <code>dispose</code>; Auswahl-Callbacks kennen <code>unitId</code>, <code>quote</code>, <code>start</code> und <code>end</code>. JavaScript verwendet <code>// @ts-check</code> und JSDoc-Typimporte. Auch der globale Einstieg des Browser-Bundles besitzt eine reine Typreferenz.</p><p>Die Tests kompilieren isolierte Anwendungen gegen die ausgelieferten Deklarationen und prüfen echte Vervollständigung sowie Hover-Texte im Language Service. Die VS-Code-Oberfläche wird dabei nicht automatisiert.</p><p><a href="../guides/library-types/">Typisierte Beispiele und Vertrag öffnen (EN)</a></p><h2>Eigene KI- oder Agent-Abläufe verbinden</h2><p>Deine Anwendung startet die Analyse und validiert die Antwort. Codepoint-Positionen in UTF-16 umrechnen, Text-ID und genaues Zitat prüfen und die Quellversion festhalten, bevor Befunde übergeben werden. Die Library stellt die Befunde dar; das Backend verwaltet Zugangsdaten, dauerhafte Entscheidungen, Vorschläge und Quelländerungen. Die Live-Bridge tauscht nur Review-Nachrichten mit dem konfigurierten Studio-Elternfenster oder Öffner aus.</p><p><a href="../guides/agent-integration/">Agent-Anbindung und Ergebnisgrenzen (EN)</a> · <a href="../guides/runner-integration/">Runner-Adapter im Studio (EN)</a></p><h2>Prüfregeln zusammenstellen</h2><p><code>@voice/writing-rules</code> liefert einen versionierten Regelkatalog, Review-Profile und zusammensetzbare Prompts. Lokale Musterprüfungen markieren Kandidaten für das Review. Deine Anwendung führt Modellanalysen aus und validiert die zurückgegebenen Befunde.</p><p><a href="../writing-patterns/">Sprachmuster und Prompts ansehen</a> · <a href="../guides/writing-rules/">Das Regelpaket einbinden</a></p><p><a href="../guides/library/">Vollständige Library-Anleitung (EN)</a> · <a href="../guides/live-bridge/">Bridge-Protokoll (EN)</a> · <a href="../docs/">Doku</a></p></section>`
  },
  { slug: "docs", title: "Voice documentation · Review, integrate and connect agents", description: "Start with a working review, embed the typed Library, or connect an agent. Find concrete file trees, JSON and API references when you need them.", en: docsIndex("en"), de: docsIndex("de") }
];
