export const escape = value => String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
export function documentPage({title,description,slug='',content,guide=false,demo=false}) {
  const prefix = slug ? '../'.repeat(slug.split('/').filter(Boolean).length) : './';
  const productPage=!guide&&(!slug||slug==='studio'||slug==='docs');
  const pageClass=guide?'guide-page':!slug?'home-page':slug==='studio'?'studio-page':slug==='writing-patterns'?'patterns-page':slug==='research'?'research-page':'';
  const navLink = ([route,en,de]) => `<a href="${prefix}${route}/"${slug===route||(guide&&route==='docs')?' aria-current="page"':''} data-en="${en}" data-de="${de}">${en}</a>`;
  const nav = `<div class="nav-tools" role="group" aria-label="Tools / Werkzeuge">${[['studio','Studio','Studio'],['library','Library','Library']].map(navLink).join('')}</div><div class="nav-resources" role="group" aria-label="Knowledge / Wissen">${[['research','Research','Forschung'],['writing-patterns','AI anti-patterns','KI-Negativmuster'],['docs','Docs','Doku']].map(navLink).join('')}</div>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><link rel="canonical" href="https://agent-orchestrator.dev/voice/${slug?slug+'/':''}"><link rel="stylesheet" href="${prefix}site.css"><link rel="stylesheet" href="${prefix}docs.css">${productPage?`<link rel="stylesheet" href="${prefix}product.css">`:""}${slug==='writing-patterns'?`<link rel="stylesheet" href="${prefix}writing-patterns.css">`:""}${slug==='research'?`<link rel="stylesheet" href="${prefix}research.css">`:""}<meta name="theme-color" content="#14271f"></head><body${pageClass?` class="${pageClass}"`:""}><a class="skip" href="#content" data-en="Skip to content" data-de="Zum Inhalt">Skip to content</a><header class="site-header"><a class="brand" href="${prefix}" aria-label="Voice home">voice <i>/</i></a><nav class="site-nav" aria-label="Main">${nav}</nav><div class="language" role="group" aria-label="Language / Sprache"><button type="button" data-locale="en" aria-pressed="true">EN</button><button type="button" data-locale="de" aria-pressed="false">DE</button></div></header><main id="content">${content}</main><footer class="site-footer"><a href="https://agent-orchestrator.dev/">Agent Orchestrator ecosystem</a><p data-en="Git and folders · Explicit source changes" data-de="Git und Ordner · Bewusste Quelländerungen">Git and folders · Explicit source changes</p><a href="${prefix}build-info.json" data-en="Build record" data-de="Build-Nachweis">Build record</a></footer>${demo?`<script src="${prefix}voice-review.js" defer></script>`:''}<script src="${prefix}site.js" defer></script>${slug==='writing-patterns'?`<script type="module" src="${prefix}writing-patterns.js"></script>`:""}${slug==='research'?`<script type="module" src="${prefix}research.js"></script>`:""}</body></html>`;
}
