export const toolExample = `import {
  createWritingToolDispatcher,
  writingReviewTools,
} from '@voice/writing-rules/tools';

const dispatcher = createWritingToolDispatcher({
  reviewContext: {
    audience: 'Developers reading the setup guide',
    goal: 'Open a folder and complete a review',
  },
});

// Register these schemas in your model's tool format.
const definitions = writingReviewTools;

// Dispatch a decoded tool call from your agent.
const result = await dispatcher.dispatch({
  name: 'compose_writing_review_prompt',
  arguments: { profile: 'public-docs', language: 'en' },
});`;

export function libraryIntroduction(locale) {
  const de = locale === 'de';
  return `<header class="page-heading"><p class="eyebrow">TypeScript · JavaScript · LLM tools</p><h1>${de?'Zwei Libraries für Textreviews.':'Two libraries for text review.'}</h1><p class="lead">${de?'Regeln und Prüf-Prompts für deinen Agenten. Markierungen und Textauswahl für deine Website. Beide Pakete lassen sich unabhängig einbinden.':'Rules and review prompts for your agent. Annotations and text selection for your website. Use either package independently.'}</p></header>
<div class="grid"><section class="card"><p class="eyebrow">Tooling · @voice/writing-rules</p><h2>${de?'Ein Textreview vorbereiten':'Prepare a text review'}</h2><p>${de?'20 Regeln mit Beispielen und Ausnahmen, vier Review-Profile, zusammensetzbare Prompts und lokale Musterprüfungen. Vier LLM-Tools machen diese Funktionen aus einem Agent-Ablauf aufrufbar.':'20 rules with examples and exceptions, four review profiles, composable prompts and local phrase checks. Four LLM tools expose these capabilities to an agent workflow.'}</p><a href="#agent-tools">${de?'Tool-Aufrufe und Beispiel':'Tool calls and example'} ↗</a></section><section class="card"><p class="eyebrow">HTML · @voice/review</p><h2>${de?'Befunde auf der Seite zeigen':'Show findings on the page'}</h2><p>${de?'Befunde am passenden Text markieren, native Textauswahl erhalten und Zitat sowie Quellposition an deine Anwendung zurückgeben. Deine Anwendung stellt Entscheidungen und Alternativen dar und speichert sie.':'Mark findings on their text, preserve native selection, and return the quote and source position to your application. Your application presents and saves decisions and alternatives.'}</p><a href="#html-review">${de?'Die HTML-Library ausprobieren':'Try the HTML library'} ↗</a></section></div>
<section class="prose" id="agent-tools"><h2>${de?'Voice als LLM-Tool verwenden':'Use Voice as an LLM tool'}</h2><p>${de?'Deine Anwendung registriert die Tool-Schemas beim Modell und übergibt dessen Aufrufe an den Dispatcher. Zielgruppe und Textziel kommen aus deiner Anwendung. Der Dispatcher liefert Regelwissen, einen Prüf-Prompt oder lokale Signale zurück.':'Your application registers the tool schemas with its model and passes returned calls to the dispatcher. It supplies the audience and writing goal. The dispatcher returns rule knowledge, a review prompt or local signals.'}</p><pre><code class="language-typescript">${toolExample}</code></pre><p>${de?'Das Beispiel läuft lokal. Deine Anwendung führt Modellaufrufe aus und validiert die Antworten. Die ESM-Pakete enthalten TypeScript-Deklarationen; sie werden im Workspace gebaut und sind noch nicht auf npm veröffentlicht.':'This example runs locally. Your application executes model requests and validates responses. The ESM packages include TypeScript declarations; build them in the workspace. They are not yet published to npm.'}</p><p><a href="../guides/writing-tools/">${de?'Tool-Schemas, Rückgaben und vollständige Beispiele':'Tool schemas, results and complete examples'} ↗</a></p>
<h2>${de?'Passende Prompts und Modellvergleiche':'Review prompts and model comparisons'}</h2><p>${de?'Wähle ein Review-Profil und bei Bedarf einzelne Regeln. Der Prüf-Prompt enthält konkrete Anweisungen, bedingte Beispiele und Fälle, in denen der Text bleiben soll. Er bezieht Zielgruppe und Ziel in den Prüfauftrag ein.':'Choose a review profile and, when needed, individual rules. Its prompt includes concrete instructions, conditional examples and cases where the text should stay. It includes the audience and writing goal in the review instructions.'}</p><p>${de?'Für die verfügbaren Modelle kann deine Anwendung gespeicherte Benchmark-Ergebnisse anbinden. Das Tool <code>get_model_comparison_evidence</code> kann je nach Nachweislage einen oder beide Vergleiche zurückgeben: die günstigste Option, die deine Qualitätskriterien erfüllt, und die höchste beobachtete Problemerkennung. Sprache, Review-Profil und Testbestand müssen passen; Fehlalarme, Quellnachweise und Grenzen gehören zum Ergebnis.':'Your application can connect retained benchmark results for its available models. The <code>get_model_comparison_evidence</code> tool can return either or both comparisons when supported by evidence: the least expensive option meeting your quality requirements, and the highest observed issue detection. Language, review profile and test cohort must match; false changes, evidence sources and limitations accompany the result.'}</p><p>${de?'Aktuell liegt kein qualifizierter Modellvergleich vor. Ohne passende Nachweise liefert das Tool <code>evidence-missing</code>. Die Library berechnet keine Rangliste; die Benchmark-Auswertung prüft gespeicherte Antworten und unabhängige menschliche Bewertungen.':'No qualified model comparison is currently available. Without matching evidence, the tool returns <code>evidence-missing</code>. The library does not compute a ranking; the benchmark evaluator assesses retained responses and independent human judgments.'}</p><p><a href="../guides/review-benchmarks/">${de?'Qualitätskriterien, Dateibaum und reproduzierbare Auswertung':'Quality criteria, file tree and reproducible evaluation'} ↗</a> · <a href="../research/#library-analysis">${de?'Forschung, Regeln und statische Analyse':'Research, rules and static analysis'} ↗</a></p></section>`;
}
